// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file apiweave/v1/auth.proto (package apiweave.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apiweave/v1/auth.proto.
 */
export const file_apiweave_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("ChZhcGl3ZWF2ZS92MS9hdXRoLnByb3RvEgthcGl3ZWF2ZS52MSJXCgtBdXRoQ29udGV4dBIVCg1hY3Rvcl91c2VyX2lkGAEgASgJEhgKEGFjdG9yX3Nlc3Npb25faWQYAiABKAkSFwoPYWN0b3JfZGV2aWNlX2lkGAMgASgJQrwBCg9jb20uYXBpd2VhdmUudjFCCUF1dGhQcm90b1ABWlFnaXRodWIuY29tL2theXNoYXJwNDIvYXBpd2VhdmUtY2xvdWQvYXBwcy9hcGkvZ2VuL3Byb3RvL2dvL2FwaXdlYXZlL3YxO2FwaXdlYXZldjGiAgNBWFiqAgtBcGl3ZWF2ZS5WMcoCC0FwaXdlYXZlXFYx4gIXQXBpd2VhdmVcVjFcR1BCTWV0YWRhdGHqAgxBcGl3ZWF2ZTo6VjFiBnByb3RvMw");

/**
 * AuthContext is the request header on every mutating RPC.
 * The server extracts and validates these fields from the request message.
 *
 * @generated from message apiweave.v1.AuthContext
 */
export type AuthContext = Message<"apiweave.v1.AuthContext"> & {
  /**
   * actor_user_id is the ULID of the authenticated user.
   *
   * @generated from field: string actor_user_id = 1;
   */
  actorUserId: string;

  /**
   * actor_session_id is the ULID of the current session.
   *
   * @generated from field: string actor_session_id = 2;
   */
  actorSessionId: string;

  /**
   * actor_device_id is the ULID of the device making the request.
   *
   * @generated from field: string actor_device_id = 3;
   */
  actorDeviceId: string;
};

/**
 * Describes the message apiweave.v1.AuthContext.
 * Use `create(AuthContextSchema)` to create a new message.
 */
export const AuthContextSchema: GenMessage<AuthContext> = /*@__PURE__*/
  messageDesc(file_apiweave_v1_auth, 0);

