// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file apiweave/v1/common.proto (package apiweave.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp as Timestamp$1 } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apiweave/v1/common.proto.
 */
export const file_apiweave_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChhhcGl3ZWF2ZS92MS9jb21tb24ucHJvdG8SC2FwaXdlYXZlLnYxIhUKBFVsaWQSDQoFdmFsdWUYASABKAkiFAoDUmV2Eg0KBXZhbHVlGAEgASgDIhMKAklkEg0KBXZhbHVlGAEgASgJIjYKCVRpbWVzdGFtcBIpCgV2YWx1ZRgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAi4QEKBUVycm9yEiUKBGNvZGUYASABKA4yFy5hcGl3ZWF2ZS52MS5FcnJvci5Db2RlEg8KB21lc3NhZ2UYAiABKAkinwEKBENvZGUSFAoQQ09ERV9VTlNQRUNJRklFRBAAEhgKFENPREVfVU5BVVRIRU5USUNBVEVEEAESEgoOQ09ERV9GT1JCSURERU4QAhISCg5DT0RFX05PVF9GT1VORBADEhEKDUNPREVfQ09ORkxJQ1QQBBIZChVDT0RFX0lOVkFMSURfQVJHVU1FTlQQBRIRCg1DT0RFX0lOVEVSTkFMEAZCvgEKD2NvbS5hcGl3ZWF2ZS52MUILQ29tbW9uUHJvdG9QAVpRZ2l0aHViLmNvbS9rYXlzaGFycDQyL2FwaXdlYXZlLWNsb3VkL2FwcHMvYXBpL2dlbi9wcm90by9nby9hcGl3ZWF2ZS92MTthcGl3ZWF2ZXYxogIDQVhYqgILQXBpd2VhdmUuVjHKAgtBcGl3ZWF2ZVxWMeICF0FwaXdlYXZlXFYxXEdQQk1ldGFkYXRh6gIMQXBpd2VhdmU6OlYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * Ulid is a 26-character Crockford Base32 ULID string.
 *
 * @generated from message apiweave.v1.Ulid
 */
export type Ulid = Message<"apiweave.v1.Ulid"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message apiweave.v1.Ulid.
 * Use `create(UlidSchema)` to create a new message.
 */
export const UlidSchema: GenMessage<Ulid> = /*@__PURE__*/
  messageDesc(file_apiweave_v1_common, 0);

/**
 * Rev is a monotonically increasing revision counter.
 *
 * @generated from message apiweave.v1.Rev
 */
export type Rev = Message<"apiweave.v1.Rev"> & {
  /**
   * @generated from field: int64 value = 1;
   */
  value: bigint;
};

/**
 * Describes the message apiweave.v1.Rev.
 * Use `create(RevSchema)` to create a new message.
 */
export const RevSchema: GenMessage<Rev> = /*@__PURE__*/
  messageDesc(file_apiweave_v1_common, 1);

/**
 * Id is a primary identifier aliased to Ulid.
 *
 * @generated from message apiweave.v1.Id
 */
export type Id = Message<"apiweave.v1.Id"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message apiweave.v1.Id.
 * Use `create(IdSchema)` to create a new message.
 */
export const IdSchema: GenMessage<Id> = /*@__PURE__*/
  messageDesc(file_apiweave_v1_common, 2);

/**
 * Timestamp re-exports google.protobuf.Timestamp for convenience.
 * Use google.protobuf.Timestamp directly in messages.
 * This message exists only to document the convention.
 *
 * @generated from message apiweave.v1.Timestamp
 */
export type Timestamp = Message<"apiweave.v1.Timestamp"> & {
  /**
   * @generated from field: google.protobuf.Timestamp value = 1;
   */
  value?: Timestamp$1 | undefined;
};

/**
 * Describes the message apiweave.v1.Timestamp.
 * Use `create(TimestampSchema)` to create a new message.
 */
export const TimestampSchema: GenMessage<Timestamp> = /*@__PURE__*/
  messageDesc(file_apiweave_v1_common, 3);

/**
 * Error is the canonical error shape returned by all services.
 *
 * @generated from message apiweave.v1.Error
 */
export type Error = Message<"apiweave.v1.Error"> & {
  /**
   * @generated from field: apiweave.v1.Error.Code code = 1;
   */
  code: Error_Code;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message apiweave.v1.Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
export const ErrorSchema: GenMessage<Error> = /*@__PURE__*/
  messageDesc(file_apiweave_v1_common, 4);

/**
 * @generated from enum apiweave.v1.Error.Code
 */
export enum Error_Code {
  /**
   * @generated from enum value: CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CODE_UNAUTHENTICATED = 1;
   */
  UNAUTHENTICATED = 1,

  /**
   * @generated from enum value: CODE_FORBIDDEN = 2;
   */
  FORBIDDEN = 2,

  /**
   * @generated from enum value: CODE_NOT_FOUND = 3;
   */
  NOT_FOUND = 3,

  /**
   * @generated from enum value: CODE_CONFLICT = 4;
   */
  CONFLICT = 4,

  /**
   * @generated from enum value: CODE_INVALID_ARGUMENT = 5;
   */
  INVALID_ARGUMENT = 5,

  /**
   * @generated from enum value: CODE_INTERNAL = 6;
   */
  INTERNAL = 6,
}

/**
 * Describes the enum apiweave.v1.Error.Code.
 */
export const Error_CodeSchema: GenEnum<Error_Code> = /*@__PURE__*/
  enumDesc(file_apiweave_v1_common, 4, 0);

