// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file apiweave/v1/device.proto (package apiweave.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { AuthContext } from "./auth_pb";
import { file_apiweave_v1_auth } from "./auth_pb";
import type { EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apiweave/v1/device.proto.
 */
export const file_apiweave_v1_device: GenFile = /*@__PURE__*/
  fileDesc("ChhhcGl3ZWF2ZS92MS9kZXZpY2UucHJvdG8SC2FwaXdlYXZlLnYxIuwBCgZEZXZpY2USCgoCaWQYASABKAkSCwoDcmV2GAIgASgDEhIKCnB1YmxpY19rZXkYAyABKAwSDQoFbGFiZWwYBCABKAkSFgoOY2xpZW50X3ZlcnNpb24YBSABKAkSLgoKY3JlYXRlZF9hdBgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKcmV2b2tlZF9hdBgIIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiRwoKRGV2aWNlTGlzdBIkCgdkZXZpY2VzGAEgAygLMhMuYXBpd2VhdmUudjEuRGV2aWNlEhMKC25leHRfY3Vyc29yGAIgASgJIoIBChVSZWdpc3RlckRldmljZVJlcXVlc3QSLgoMYXV0aF9jb250ZXh0GAEgASgLMhguYXBpd2VhdmUudjEuQXV0aENvbnRleHQSEgoKcHVibGljX2tleRgCIAEoDBINCgVsYWJlbBgDIAEoCRIWCg5jbGllbnRfdmVyc2lvbhgEIAEoCSJYChNSZXZva2VEZXZpY2VSZXF1ZXN0Ei4KDGF1dGhfY29udGV4dBgBIAEoCzIYLmFwaXdlYXZlLnYxLkF1dGhDb250ZXh0EhEKCWRldmljZV9pZBgCIAEoCTLkAQoNRGV2aWNlU2VydmljZRJJCg5SZWdpc3RlckRldmljZRIiLmFwaXdlYXZlLnYxLlJlZ2lzdGVyRGV2aWNlUmVxdWVzdBoTLmFwaXdlYXZlLnYxLkRldmljZRI+CgtMaXN0RGV2aWNlcxIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoXLmFwaXdlYXZlLnYxLkRldmljZUxpc3QSSAoMUmV2b2tlRGV2aWNlEiAuYXBpd2VhdmUudjEuUmV2b2tlRGV2aWNlUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eUK+AQoPY29tLmFwaXdlYXZlLnYxQgtEZXZpY2VQcm90b1ABWlFnaXRodWIuY29tL2theXNoYXJwNDIvYXBpd2VhdmUtY2xvdWQvYXBwcy9hcGkvZ2VuL3Byb3RvL2dvL2FwaXdlYXZlL3YxO2FwaXdlYXZldjGiAgNBWFiqAgtBcGl3ZWF2ZS5WMcoCC0FwaXdlYXZlXFYx4gIXQXBpd2VhdmVcVjFcR1BCTWV0YWRhdGHqAgxBcGl3ZWF2ZTo6VjFiBnByb3RvMw", [file_apiweave_v1_auth, file_google_protobuf_empty, file_google_protobuf_timestamp]);

/**
 * Device represents a registered client device.
 *
 * @generated from message apiweave.v1.Device
 */
export type Device = Message<"apiweave.v1.Device"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: int64 rev = 2;
   */
  rev: bigint;

  /**
   * public_key is the device Ed25519 public key (raw bytes).
   *
   * @generated from field: bytes public_key = 3;
   */
  publicKey: Uint8Array;

  /**
   * @generated from field: string label = 4;
   */
  label: string;

  /**
   * @generated from field: string client_version = 5;
   */
  clientVersion: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 7;
   */
  updatedAt?: Timestamp | undefined;

  /**
   * revoked_at is set when the device is revoked; zero otherwise.
   *
   * @generated from field: google.protobuf.Timestamp revoked_at = 8;
   */
  revokedAt?: Timestamp | undefined;
};

/**
 * Describes the message apiweave.v1.Device.
 * Use `create(DeviceSchema)` to create a new message.
 */
export const DeviceSchema: GenMessage<Device> = /*@__PURE__*/
  messageDesc(file_apiweave_v1_device, 0);

/**
 * DeviceList is a paginated list of devices.
 *
 * @generated from message apiweave.v1.DeviceList
 */
export type DeviceList = Message<"apiweave.v1.DeviceList"> & {
  /**
   * @generated from field: repeated apiweave.v1.Device devices = 1;
   */
  devices: Device[];

  /**
   * @generated from field: string next_cursor = 2;
   */
  nextCursor: string;
};

/**
 * Describes the message apiweave.v1.DeviceList.
 * Use `create(DeviceListSchema)` to create a new message.
 */
export const DeviceListSchema: GenMessage<DeviceList> = /*@__PURE__*/
  messageDesc(file_apiweave_v1_device, 1);

/**
 * RegisterDeviceRequest registers a new device for the current user.
 *
 * @generated from message apiweave.v1.RegisterDeviceRequest
 */
export type RegisterDeviceRequest = Message<"apiweave.v1.RegisterDeviceRequest"> & {
  /**
   * @generated from field: apiweave.v1.AuthContext auth_context = 1;
   */
  authContext?: AuthContext | undefined;

  /**
   * @generated from field: bytes public_key = 2;
   */
  publicKey: Uint8Array;

  /**
   * @generated from field: string label = 3;
   */
  label: string;

  /**
   * @generated from field: string client_version = 4;
   */
  clientVersion: string;
};

/**
 * Describes the message apiweave.v1.RegisterDeviceRequest.
 * Use `create(RegisterDeviceRequestSchema)` to create a new message.
 */
export const RegisterDeviceRequestSchema: GenMessage<RegisterDeviceRequest> = /*@__PURE__*/
  messageDesc(file_apiweave_v1_device, 2);

/**
 * RevokeDeviceRequest revokes a device.
 *
 * @generated from message apiweave.v1.RevokeDeviceRequest
 */
export type RevokeDeviceRequest = Message<"apiweave.v1.RevokeDeviceRequest"> & {
  /**
   * @generated from field: apiweave.v1.AuthContext auth_context = 1;
   */
  authContext?: AuthContext | undefined;

  /**
   * @generated from field: string device_id = 2;
   */
  deviceId: string;
};

/**
 * Describes the message apiweave.v1.RevokeDeviceRequest.
 * Use `create(RevokeDeviceRequestSchema)` to create a new message.
 */
export const RevokeDeviceRequestSchema: GenMessage<RevokeDeviceRequest> = /*@__PURE__*/
  messageDesc(file_apiweave_v1_device, 3);

/**
 * DeviceService manages device registration and revocation.
 *
 * @generated from service apiweave.v1.DeviceService
 */
export const DeviceService: GenService<{
  /**
   * @generated from rpc apiweave.v1.DeviceService.RegisterDevice
   */
  registerDevice: {
    methodKind: "unary";
    input: typeof RegisterDeviceRequestSchema;
    output: typeof DeviceSchema;
  },
  /**
   * @generated from rpc apiweave.v1.DeviceService.ListDevices
   */
  listDevices: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof DeviceListSchema;
  },
  /**
   * @generated from rpc apiweave.v1.DeviceService.RevokeDevice
   */
  revokeDevice: {
    methodKind: "unary";
    input: typeof RevokeDeviceRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_apiweave_v1_device, 0);

