// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=js"
// @generated from file apiweave/v1/sync.proto (package apiweave.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apiweave/v1/sync.proto.
 */
export const file_apiweave_v1_sync: GenFile = /*@__PURE__*/
  fileDesc("ChZhcGl3ZWF2ZS92MS9zeW5jLnByb3RvEgthcGl3ZWF2ZS52MSJwCgxTeW5jRW52ZWxvcGUSEQoJcmVjb3JkX2lkGAEgASgJEgsKA3JldhgCIAEoAxIfCgJvcBgDIAEoDjITLmFwaXdlYXZlLnYxLlN5bmNPcBIPCgdwYXlsb2FkGAQgASgMEg4KBmN1cnNvchgFIAEoAyI3CghQcm90b2NvbBIPCgd2ZXJzaW9uGAEgASgFEhoKEnN1cHBvcnRlZF92ZXJzaW9ucxgCIAMoBSpJCgZTeW5jT3ASFwoTU1lOQ19PUF9VTlNQRUNJRklFRBAAEhIKDlNZTkNfT1BfVVBTRVJUEAESEgoOU1lOQ19PUF9ERUxFVEUQAkK8AQoPY29tLmFwaXdlYXZlLnYxQglTeW5jUHJvdG9QAVpRZ2l0aHViLmNvbS9rYXlzaGFycDQyL2FwaXdlYXZlLWNsb3VkL2FwcHMvYXBpL2dlbi9wcm90by9nby9hcGl3ZWF2ZS92MTthcGl3ZWF2ZXYxogIDQVhYqgILQXBpd2VhdmUuVjHKAgtBcGl3ZWF2ZVxWMeICF0FwaXdlYXZlXFYxXEdQQk1ldGFkYXRh6gIMQXBpd2VhdmU6OlYxYgZwcm90bzM");

/**
 * SyncEnvelope is a single replication delta.
 *
 * @generated from message apiweave.v1.SyncEnvelope
 */
export type SyncEnvelope = Message<"apiweave.v1.SyncEnvelope"> & {
  /**
   * @generated from field: string record_id = 1;
   */
  recordId: string;

  /**
   * @generated from field: int64 rev = 2;
   */
  rev: bigint;

  /**
   * @generated from field: apiweave.v1.SyncOp op = 3;
   */
  op: SyncOp;

  /**
   * @generated from field: bytes payload = 4;
   */
  payload: Uint8Array;

  /**
   * @generated from field: int64 cursor = 5;
   */
  cursor: bigint;
};

/**
 * Describes the message apiweave.v1.SyncEnvelope.
 * Use `create(SyncEnvelopeSchema)` to create a new message.
 */
export const SyncEnvelopeSchema: GenMessage<SyncEnvelope> = /*@__PURE__*/
  messageDesc(file_apiweave_v1_sync, 0);

/**
 * Protocol advertises the sync protocol version and compatible versions.
 *
 * @generated from message apiweave.v1.Protocol
 */
export type Protocol = Message<"apiweave.v1.Protocol"> & {
  /**
   * @generated from field: int32 version = 1;
   */
  version: number;

  /**
   * @generated from field: repeated int32 supported_versions = 2;
   */
  supportedVersions: number[];
};

/**
 * Describes the message apiweave.v1.Protocol.
 * Use `create(ProtocolSchema)` to create a new message.
 */
export const ProtocolSchema: GenMessage<Protocol> = /*@__PURE__*/
  messageDesc(file_apiweave_v1_sync, 1);

/**
 * SyncOp describes the mutation kind carried by a SyncEnvelope.
 *
 * @generated from enum apiweave.v1.SyncOp
 */
export enum SyncOp {
  /**
   * @generated from enum value: SYNC_OP_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SYNC_OP_UPSERT = 1;
   */
  UPSERT = 1,

  /**
   * @generated from enum value: SYNC_OP_DELETE = 2;
   */
  DELETE = 2,
}

/**
 * Describes the enum apiweave.v1.SyncOp.
 */
export const SyncOpSchema: GenEnum<SyncOp> = /*@__PURE__*/
  enumDesc(file_apiweave_v1_sync, 0);

