// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file apiweave/v1/team.proto (package apiweave.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { AuthContext } from "./auth_pb";
import { file_apiweave_v1_auth } from "./auth_pb";
import type { EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apiweave/v1/team.proto.
 */
export const file_apiweave_v1_team: GenFile = /*@__PURE__*/
  fileDesc("ChZhcGl3ZWF2ZS92MS90ZWFtLnByb3RvEgthcGl3ZWF2ZS52MSKkAQoEVGVhbRIKCgJpZBgBIAEoCRILCgNyZXYYAiABKAMSDAoEbmFtZRgDIAEoCRIVCg1vd25lcl91c2VyX2lkGAQgASgJEi4KCmNyZWF0ZWRfYXQYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYBiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIkEKCFRlYW1MaXN0EiAKBXRlYW1zGAEgAygLMhEuYXBpd2VhdmUudjEuVGVhbRITCgtuZXh0X2N1cnNvchgCIAEoCSJRChFDcmVhdGVUZWFtUmVxdWVzdBIuCgxhdXRoX2NvbnRleHQYASABKAsyGC5hcGl3ZWF2ZS52MS5BdXRoQ29udGV4dBIMCgRuYW1lGAIgASgJIiEKDkdldFRlYW1SZXF1ZXN0Eg8KB3RlYW1faWQYASABKAkikAEKGFRyYW5zZmVyT3duZXJzaGlwUmVxdWVzdBIuCgxhdXRoX2NvbnRleHQYASABKAsyGC5hcGl3ZWF2ZS52MS5BdXRoQ29udGV4dBIPCgd0ZWFtX2lkGAIgASgJEhkKEW5ld19vd25lcl91c2VyX2lkGAMgASgJEhgKEGV4cGVjdGVkX3ZlcnNpb24YBCABKAMymQIKC1RlYW1TZXJ2aWNlEj8KCkNyZWF0ZVRlYW0SHi5hcGl3ZWF2ZS52MS5DcmVhdGVUZWFtUmVxdWVzdBoRLmFwaXdlYXZlLnYxLlRlYW0SOQoHR2V0VGVhbRIbLmFwaXdlYXZlLnYxLkdldFRlYW1SZXF1ZXN0GhEuYXBpd2VhdmUudjEuVGVhbRI6CglMaXN0VGVhbXMSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaFS5hcGl3ZWF2ZS52MS5UZWFtTGlzdBJSChFUcmFuc2Zlck93bmVyc2hpcBIlLmFwaXdlYXZlLnYxLlRyYW5zZmVyT3duZXJzaGlwUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eUK8AQoPY29tLmFwaXdlYXZlLnYxQglUZWFtUHJvdG9QAVpRZ2l0aHViLmNvbS9rYXlzaGFycDQyL2FwaXdlYXZlLWNsb3VkL2FwcHMvYXBpL2dlbi9wcm90by9nby9hcGl3ZWF2ZS92MTthcGl3ZWF2ZXYxogIDQVhYqgILQXBpd2VhdmUuVjHKAgtBcGl3ZWF2ZVxWMeICF0FwaXdlYXZlXFYxXEdQQk1ldGFkYXRh6gIMQXBpd2VhdmU6OlYxYgZwcm90bzM", [file_apiweave_v1_auth, file_google_protobuf_empty, file_google_protobuf_timestamp]);

/**
 * Team is a grouping of users that owns workspaces.
 *
 * @generated from message apiweave.v1.Team
 */
export type Team = Message<"apiweave.v1.Team"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: int64 rev = 2;
   */
  rev: bigint;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string owner_user_id = 4;
   */
  ownerUserId: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 6;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message apiweave.v1.Team.
 * Use `create(TeamSchema)` to create a new message.
 */
export const TeamSchema: GenMessage<Team> = /*@__PURE__*/
  messageDesc(file_apiweave_v1_team, 0);

/**
 * TeamList is a paginated list of teams.
 *
 * @generated from message apiweave.v1.TeamList
 */
export type TeamList = Message<"apiweave.v1.TeamList"> & {
  /**
   * @generated from field: repeated apiweave.v1.Team teams = 1;
   */
  teams: Team[];

  /**
   * @generated from field: string next_cursor = 2;
   */
  nextCursor: string;
};

/**
 * Describes the message apiweave.v1.TeamList.
 * Use `create(TeamListSchema)` to create a new message.
 */
export const TeamListSchema: GenMessage<TeamList> = /*@__PURE__*/
  messageDesc(file_apiweave_v1_team, 1);

/**
 * CreateTeamRequest creates a new team.
 *
 * @generated from message apiweave.v1.CreateTeamRequest
 */
export type CreateTeamRequest = Message<"apiweave.v1.CreateTeamRequest"> & {
  /**
   * @generated from field: apiweave.v1.AuthContext auth_context = 1;
   */
  authContext?: AuthContext | undefined;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message apiweave.v1.CreateTeamRequest.
 * Use `create(CreateTeamRequestSchema)` to create a new message.
 */
export const CreateTeamRequestSchema: GenMessage<CreateTeamRequest> = /*@__PURE__*/
  messageDesc(file_apiweave_v1_team, 2);

/**
 * GetTeamRequest fetches a team by ID.
 *
 * @generated from message apiweave.v1.GetTeamRequest
 */
export type GetTeamRequest = Message<"apiweave.v1.GetTeamRequest"> & {
  /**
   * @generated from field: string team_id = 1;
   */
  teamId: string;
};

/**
 * Describes the message apiweave.v1.GetTeamRequest.
 * Use `create(GetTeamRequestSchema)` to create a new message.
 */
export const GetTeamRequestSchema: GenMessage<GetTeamRequest> = /*@__PURE__*/
  messageDesc(file_apiweave_v1_team, 3);

/**
 * TransferOwnershipRequest transfers team ownership to another user.
 *
 * @generated from message apiweave.v1.TransferOwnershipRequest
 */
export type TransferOwnershipRequest = Message<"apiweave.v1.TransferOwnershipRequest"> & {
  /**
   * @generated from field: apiweave.v1.AuthContext auth_context = 1;
   */
  authContext?: AuthContext | undefined;

  /**
   * @generated from field: string team_id = 2;
   */
  teamId: string;

  /**
   * @generated from field: string new_owner_user_id = 3;
   */
  newOwnerUserId: string;

  /**
   * expected_version is the team's current rev for optimistic concurrency.
   *
   * @generated from field: int64 expected_version = 4;
   */
  expectedVersion: bigint;
};

/**
 * Describes the message apiweave.v1.TransferOwnershipRequest.
 * Use `create(TransferOwnershipRequestSchema)` to create a new message.
 */
export const TransferOwnershipRequestSchema: GenMessage<TransferOwnershipRequest> = /*@__PURE__*/
  messageDesc(file_apiweave_v1_team, 4);

/**
 * TeamService manages teams.
 *
 * @generated from service apiweave.v1.TeamService
 */
export const TeamService: GenService<{
  /**
   * @generated from rpc apiweave.v1.TeamService.CreateTeam
   */
  createTeam: {
    methodKind: "unary";
    input: typeof CreateTeamRequestSchema;
    output: typeof TeamSchema;
  },
  /**
   * @generated from rpc apiweave.v1.TeamService.GetTeam
   */
  getTeam: {
    methodKind: "unary";
    input: typeof GetTeamRequestSchema;
    output: typeof TeamSchema;
  },
  /**
   * @generated from rpc apiweave.v1.TeamService.ListTeams
   */
  listTeams: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof TeamListSchema;
  },
  /**
   * @generated from rpc apiweave.v1.TeamService.TransferOwnership
   */
  transferOwnership: {
    methodKind: "unary";
    input: typeof TransferOwnershipRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_apiweave_v1_team, 0);

